spring:
  kafka:
    bootstrap-servers: pkc-921jm.us-east-2.aws.confluent.cloud:9092
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        jaas:
          config: >
            org.apache.kafka.common.security.plain.PlainLoginModule required
            username='${KAFKA_USERNAME}' password='${KAFKA_PASSWORD}';
        mechanism: PLAIN
    consumer:
      group-id: code-consumer-group
      auto-offset-reset: earliest

  application:
    name: code-judge
  datasource:
    url: jdbc:mysql://switchback.proxy.rlwy.net:49925/railway
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL 드라이버
    username: root
    password: RClsobdReFppPUFNEaMYCXjBanOBehpC
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true # 실행되는 SQL 쿼리 출력
    properties:
      hibernate:
        "[format_sql]": true # SQL 포맷팅
        dialect: org.hibernate.dialect.MySQLDialect # MySQL에 맞는 Hibernate 방언 설정

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

server:
  port: ${PORT:8080}
